# Random Forsest Apply on Phising Dataset

In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [2]:
sns.set()

In [3]:
df = pd.read_csv("PycharmProjects/Ruba Project final_datasets/ruba_phising_data_set_build_final.csv", sep=",")
df.head()

HTTPS STATUS  AT THE RATE CHECK  IP ADDRESS PRESENT  DOT COUNT  \
0             0                  0                   0          2   
1             0                  0                   0          6   
2             0                  0                   0          1   
3             0                  0                   0          2   
4             0                  0                   1          3   

   SLASH COUNT  DASH CHECK  LENGTH OF HOST NAME  SLASH CHECK  PHISHING STATUS  
0            3           0                    0            0                1  
1            2           0                    1            0                1  
2            4           0                    0            0                1  
3            3           0                    0            0                1  
4            2           0                    0            0                1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2015 entries, 0 to 2014
Data columns (total 9 columns):
HTTPS STATUS           2015 non-null int64
AT THE RATE CHECK      2015 non-null int64
IP ADDRESS PRESENT     2015 non-null int64
DOT COUNT              2015 non-null int64
SLASH COUNT            2015 non-null int64
DASH CHECK             2015 non-null int64
LENGTH OF HOST NAME    2015 non-null int64
SLASH CHECK            2015 non-null int64
PHISHING STATUS        2015 non-null int64
dtypes: int64(9)
memory usage: 141.8 KB


In [5]:
df.describe()

HTTPS STATUS  AT THE RATE CHECK  IP ADDRESS PRESENT    DOT COUNT  \
count   2015.000000        2015.000000         2015.000000  2015.000000   
mean       0.046154           0.011911            0.006452     2.498759   
std        0.209870           0.108511            0.080082     1.246594   
min        0.000000           0.000000            0.000000     1.000000   
25%        0.000000           0.000000            0.000000     2.000000   
50%        0.000000           0.000000            0.000000     2.000000   
75%        0.000000           0.000000            0.000000     3.000000   
max        1.000000           1.000000            1.000000    15.000000   

       SLASH COUNT   DASH CHECK  LENGTH OF HOST NAME  SLASH CHECK  \
count  2015.000000  2015.000000          2015.000000  2015.000000   
mean      2.312655     0.244665             0.123573     0.057072   
std       1.742772     0.429995             0.329176     0.232038   
min       0.000000     0.000000             0.000000     0.000000   
25%       1.000000     0.000000             0.000000     0.000000   
50%       2.000000     0.000000             0.000000     0.000000   
75%       3.000000     0.000000             0.000000     0.000000   
max      14.000000     1.000000             1.000000     1.000000   

       PHISHING STATUS  
count      2015.000000  
mean          0.495285  
std           0.500102  
min           0.000000  
25%           0.000000  
50%           0.000000  
75%           1.000000  
max           1.000000

# Create Model

# Split The Data Set

In [39]:
y = df["PHISHING STATUS"]

In [52]:
X = df[["HTTPS STATUS","AT THE RATE CHECK","IP ADDRESS PRESENT","DOT COUNT","SLASH COUNT","DASH CHECK","LENGTH OF HOST NAME","SLASH CHECK"]]

In [53]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split


In [54]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 0, test_size=0.2, stratify=y)

In [55]:
rf = RandomForestClassifier(n_estimators=1000, max_features= 4,criterion='entropy', random_state=42)
rf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features=4, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=None,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [56]:
y_Pred = rf.predict(X_test)

In [57]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_Pred)
print (cm)

[[167  36]
 [ 28 172]]


In [58]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_Pred))

0.8411910669975186


# Save Model

In [61]:
import pickle 
  
# Save the trained model as a pickle string. 
saved_model = pickle.dumps(rf) 
  
# Load the pickled model 
rf_from_pickle = pickle.loads(saved_model) 
  
# Use the loaded pickled model to make predictions 
rf_from_pickle.predict(X_test) 

array([0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,

In [63]:
from sklearn.externals import joblib 
  
# Save the model as a pickle in a file 
joblib.dump(rf, 'model_rf_1.pkl') 
  
# Load the model from the file 
rf_from_joblib = joblib.load('model_rf_1.pkl')  
  
# Use the loaded model to make predictions 
rf_from_joblib.predict(X_test) 

array([0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,

In [75]:
# Load the model from the file 
model_1 = joblib.load('model_rf_1.pkl')
model_1.predict(np.array([0, 0, 0, 3, 1, 1, 0, 0]).reshape(1, -1))

array([1])